permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: Release Build
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - uses: actions/checkout@master
      - name: Build Snapshot & Publish to Registry
        uses: jen20/action-docker-build@v1
        with:
          repository: pulumi/pulumi-build-container
          buildkit: true
          username: pulumibot
          password: ${{ steps.esc-secrets.outputs.DOCKER_HUB_PASSWORD }}
          tag-latest: true
          additional-tags: ${{ github.ref }}
